services:
  foundry:
    hostname: foundry-ci
    build:
      context: ..
      dockerfile: ./docker/dockerfile
      additional_contexts:
        world-seed: ../world-seed
      secrets:
        - foundry_license
      args:
        FOUNDRY_VERSION: ${FOUNDRY_VERSION}
        QUENCH_MODULE_URL: ${QUENCH_MODULE_URL}
    ports:
      - "30000:30000"
    volumes:
      - ../build:/data/Data/systems/cosmere-rpg

    secrets:
      - source: foundry_license
        target: /data/Config/license.json

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000"]
      interval: 5s
      timeout: 10s
      retries: 12

secrets:
  foundry_license:
    file: ../secrets/license.json