name: "Milestone Binder"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: Code-Hex/auto-milestone-binder@v1.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
